# Creation Of Array Using Numpy

In [1]:
# Practical No:5

In [2]:
#Aim:To Perform Array Creation In Numpy

In [1]:
#Name: Punam S.Somkuwar
#Roll NO.:64
#Sec:C
#Subject:ET-1
#Date:9/08/2024

In [6]:
import numpy as np

In [7]:
array_1d = np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]


In [8]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
zeros_array = np.zeros((3,3)) 
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones_array = np.ones((2,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#Start,Stop,Step
range_array =np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]
